spring:
  application:
    name: everflow-news
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      time-to-live: 300000
  redis:
    host: localhost
    port:  6379


news-api:
  url: https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=57f4696d8c28484f849bc09108670849


mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/everflow
    username: root
    password: admin@123
    driver-class-name: com.mysql.jdbc.Driver


#this will use for server monitoring
management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,threaddump,prometheus,heapdump"